### ISSUE TITLE
Cata Classic History error

### ISSUE THREAD

**Issue by Road-block** [MrFox42/minarch#14]
1x ...dOns/MinimalArchaeology/addon/components/History.lua:153: attempt to index field '?' (a nil value)
[string "@MinimalArchaeology/addon/components/History.lua"]:153: in function <...dOns/MinimalArchaeology/addon/components/History.lua:146>
[string "=[C]"]: in function `Show'
[string "@MinimalArchaeology/addon/components/History.lua"]:933: in function `ShowHistory'
[string "@MinimalArchaeology/addon/components/History.lua"]:942: in function `Toggle'
[string "*MATemplates.xml:130_OnClick"]:1: in function <[string "*MATemplates.xml:130_OnClick"]:1>

Locals:
digSite = "Terror Wing Fossil Field"
distance = 3265.669910
digSiteData = <table> {
 y = "54.218274354935"
 uiMapID = 1428
 zone = "Burning Steppes"
 subzone = "Terror Wing Path"
 x = "79.357570409775"
 race = "Fossil"
 raceId = 8
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 10
(*temporary) = 10
(*temporary) = "attempt to index field '?' (a nil value)"
MinArch = <table> {
 ShowWindowButtonTooltip = <function> defined @MinimalArchaeology/addon/shared/Common.lua:256
 InitDigsites = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:60
 DimADIButtons = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:435
 CreateHistoryList = <function> defined @MinimalArchaeology/addon/components/History.lua:586
 HideNext = false
 GetInternalContId = <function> defined @MinimalArchaeology/addon/shared/Common.lua:119
 TestForMissingDigsites = <function> defined @MinimalArchaeology/addon/shared/Common.lua:262
 GetHistory = <function> defined @MinimalArchaeology/addon/components/History.lua:306
 ClearUiWaypoint = <function> defined @MinimalArchaeology/addon/components/Navigation.lua:41
 EventHist = <function> defined @MinimalArchaeology/addon/core/Events.lua:163
 GetUiMapIdByContId = <function> defined @MinimalArchaeology/addon/shared/Common.lua:140
 ShowArtifactTooltip = <function> defined @MinimalArchaeology/addon/components/Main.lua:451
 InitDatabase = <function> defined @MinimalArchaeology/addon/core/Init.lua:88
 TrackingChanged = <function> defined @MinimalArchaeology/addon/core/Events.lua:302
 HideHistory = <function> defined @MinimalArchaeology/addon/components/History.lua:924
 autoWaypoint = <table> {
 }
 SetRelevancyToggleButtonTexture = <function> defined @MinimalArchaeology/addon/components/Main.lua:5
 SetWayToNearestDigsite = <function> defined @MinimalArchaeology/addon/components/Navigation.lua:53
 RacesLoaded = true
 firstRun = false
 MapContinents = <table> {
 }
 DigsiteLocales = <table> {
 }
 ShowOnSurvey = true
 HelperFrame = MinArchHelper {
 }
 Options = <table> {
 }
 ShowHistory = <function> defined @MinimalArchaeology/addon/components/History.lua:929
 GetOrCreateMinArchMapFrame = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:568
 LoadItemDetails = <function> defined @MinimalArchaeology/addon/components/History.lua:182
 CommonFrameScale = <function> defined @MinimalArchaeology/addon/shared/Common.lua:77
 InitHist = <function> defined @MinimalArchaeology/addon/components/History.lua:133
 IsTomTomAvailable = <function> defined @MinimalArchaeology/addon/components/Navigation.lua:6
 db = <table> {
 }
 defaults = <table> {
 }
 ArchaeologyRaces = <table> {
 }
 HasPristine = <table> {
 }
 MaineEventHideAfterDigsite = <function> defined @MinimalArchaeology/addon/core/Events.lua:239
 ShowInDigsite = true
 InitLDB = <function> defined @MinimalArchaeology/addon/components/DataBroker.lua:7
 HideDigsites = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:718
 ClearAllDigsiteWaypoints = <function> defined @MinimalArchaeology/addon/components/Navigation.lua:100
 SetDynamicDefaults = <function> defined @MinimalArchaeology/addon/core/Init.lua:64
 UpdateMain = <function> defined @MinimalArchaeology/addon/components/Main.lua:392
 IsNearDigSite = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:564
 SetWayToDigsiteOnClick = <function> defined @MinimalArchaeology/addon/components/Navigation.lua:72
 IsNavigationEnabled = <function> defined @MinimalArchaeology/addon/components/Navigation.lua:10
 GetRaceNameByBranchId = <

**Comment by MrFox42** [comment]
Thank you, should be fixed in v10.2.9
