### ISSUE TITLE
Feature : Total of resolved artefacts by race 

### ISSUE THREAD

**Issue by Axel303** [MrFox42/minarch#15]
Hello,
I would like to first thanks you for this nice add-on.

Do you think that would be possible to add the total of resolved artefacts by race?

![image](https://github.com/MrFox42/minarch/assets/28088055/1e931e9b-8a7c-495f-b574-2a1f9f705329)

I was able to do it myself with a "print()" in the code in history.lua line 685

local totalForThisRace=0;  
for _, gparams in ipairs(groups) do
     ....
               -- Set Progress
                local progressState = MINARCH_PROGRESS_UNKNOWN;
                local achievementState = MINARCH_ACHIPROGRESS_NONE;
                if not details.firstcomplete then
                    frame.progress.text:SetText("0");
                    frame.progress.text:SetTextColor(GRAY_FONT_COLOR.r, GRAY_FONT_COLOR.g, GRAY_FONT_COLOR.b, 1)
                elseif MinArch.artifacts[RaceID].project == details.artifactname then
                    if not details.totalcomplete or details.totalcomplete == 0 then
                        frame.progress.text:SetText("#1")
                    else
                        totalForThisRace = totalForThisRace+ 1; <== THIS
                        frame.progress.text:SetText("#" .. (details.totalcomplete + 1))
                    end
                    frame.progress.text:SetTextColor(1.0, 0.8, 0.0, 1.0)
                    progressState = MINARCH_PROGRESS_CURRENT;
                else
                    totalForThisRace=totalForThisRace+details.totalcomplete <== THIS
                    frame.progress.text:SetText("x" .. details.totalcomplete)
                    frame.progress.text:SetTextColor(0.0, 1.0, 0.0, 1.0)
                    progressState = MINARCH_PROGRESS_KNOWN;
                end
...
   print(totalForThisRace)

----

Thanks for the reading

**Comment by MrFox42** [comment]
Hi, sure, I'll implement this in an upcoming release

**Comment by MrFox42** [comment]
Implemented in v10.2.10, feel free to reopen this issue if you encounter any problems, or have any more suggestions on this.

Please note that a bug in Blizzard's API returns incorrect data right after solving an artifact, which messes up total counts. A /reload solves this.
