### ISSUE TITLE
Navigation.lua:59: attempt to compare number with nil

### ISSUE THREAD

**Issue by Ookami313** [MrFox42/minarch#19]
Updated to the 10.2.13 beta and whenever I take a flightpath, as soon as I land I receive the following error. Thanks.

7x ...s/MinimalArchaeology/addon/components/Navigation.lua:59: attempt to compare number with nil
[string "@MinimalArchaeology/addon/components/Navigation.lua"]:59: in function `SetWayToNearestDigsite'
[string "@MinimalArchaeology/addon/core/Events.lua"]:288: in function `EventDigsites'
[string "@MinimalArchaeology/addon/components/Digsites.lua"]:121: in function <...Ons/MinimalArchaeology/addon/components/Digsites.lua:120>

Locals:
self = <table> {
 GetNearestFlightMaster = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:1002
 RefreshCrateButtonGlow = <function> defined @MinimalArchaeology/addon/shared/CrateButton.lua:22
 InitDigsites = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:62
 DimADIButtons = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:445
 hiddenButton = MinArchHiddenSurveyButton {
 }
 HideNext = false
 GetInternalContId = <function> defined @MinimalArchaeology/addon/shared/Common.lua:120
 DimHistoryButtons = <function> defined @MinimalArchaeology/addon/components/History.lua:923
 HistoryButtonTooltip = <function> defined @MinimalArchaeology/addon/components/History.lua:989
 ClearUiWaypoint = <function> defined @MinimalArchaeology/addon/components/Navigation.lua:41
 OpenWindow = <function> defined @MinimalArchaeology/addon/components/Main.lua:594
 IsItemDetailsLoaded = <function> defined @MinimalArchaeology/addon/components/History.lua:208
 ShowArtifactTooltip = <function> defined @MinimalArchaeology/addon/components/Main.lua:478
 InitDatabase = <function> defined @MinimalArchaeology/addon/core/Init.lua:100
 TrackingChanged = <function> defined @MinimalArchaeology/addon/core/Events.lua:355
 HideHistory = <function> defined @MinimalArchaeology/addon/components/History.lua:995
 SetRelevancyToggleButtonTexture = <function> defined @MinimalArchaeology/addon/components/Main.lua:5
 SetWayToNearestDigsite = <function> defined @MinimalArchaeology/addon/components/Navigation.lua:53
 LoadRaceInfo = <function> defined @MinimalArchaeology/addon/shared/Common.lua:268
 firstRun = false
 ShowWindowButtonTooltip = <function> defined @MinimalArchaeology/addon/shared/Common.lua:287
 MapContinents = <table> {
 }
 UpdateArchaeologySkillBar = <function> defined @MinimalArchaeology/addon/components/Main.lua:193
 ShowOnSurvey = true
 CreateHistoryList = <function> defined @MinimalArchaeology/addon/components/History.lua:637
 TestForMissingDigsites = <function> defined @MinimalArchaeology/addon/shared/Common.lua:293
 DigsiteMapTooltip = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:935
 GetOrCreateMinArchMapFrame = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:657
 LoadItemDetails = <function> defined @MinimalArchaeology/addon/components/History.lua:212
 CommonFrameScale = <function> defined @MinimalArchaeology/addon/shared/Common.lua:78
 SetIcon = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:856
 IsTomTomAvailable = <function> defined @MinimalArchaeology/addon/components/Navigation.lua:6
 db = <table> {
 }
 GetHistory = <function> defined @MinimalArchaeology/addon/components/History.lua:340
 ArchaeologyRaces = <table> {
 }
 HasPristine = <table> {
 }
 HistoryTooltip = <function> defined @MinimalArchaeology/addon/components/History.lua:931
 ShowInDigsite = true
 InitLDB = <function> defined @MinimalArchaeology/addon/components/DataBroker.lua:7
 HideDigsites = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:1058
 EventHist = <function> defined @MinimalArchaeology/addon/core/Events.lua:171
 SetDynamicDefaults = <function> defined @MinimalArchaeology/addon/core/Init.lua:76
 HistoryListLoaded = <table> {
 }
 GetOrCreateMinArchTaxiMapFrame = <function> defined @MinimalArchaeology/addon/components/Digsites.lua:665
 GetUiMapIdByContId = <function> defined @MinimalArchaeology/addon/shared/Common.lua:141
 RacesLoaded = true
 GetR

**Comment by MrFox42** [comment]
Thank you, should be fixed in the latest beta release.
