### ISSUE TITLE
[bug?] Nearby site not in Relevancy list

### ISSUE THREAD

**Issue by tflo** [MrFox42/minarch#3]
I am just near a Night Elf site (1317 yards) and it is not showing up in the Relevancy list, albeit “Available nearby” is selected. The site is correctly shown in the LDB display, and also clicking the waypoint button creates a waypoint to that digsite.

_I guess_ the reason for this is that the toon has zero collected Night Elf fragments.

Is this intentional or a bug?

(The behavior I had expected, is that it shows me _all_ nearby available sites, if that relevancy criterion is selected. Independently if I have zero or 200 fragments.)

– Tom

**Comment by MrFox42** [comment]
There might be some issues with fresh toons I always wanted to look into, but kept forgetting. I'll look into it now.

**Comment by MrFox42** [comment]
Should be fixed in v9.0.3.1
