### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by SirLagardere** [MrFox42/minarch#4]
Hello,
The true french translation for "Digsite: The Far Reach" is "Site de fouilles : Les confins Lointains"
(ie ["Digsite: The Far Reach"] = "Site de fouilles : Les confins Lointains")

**Comment by MrFox42** [comment]
Thank you, the fix will be included in an upcoming release (next week probably).

**Comment by MrFox42** [comment]
Fix released in 9.0.3.4
