### ISSUE TITLE
Attach zip file to releases

### ISSUE THREAD

**Issue by marthammor** [MrFox42/minarch#8]
Please attach a zip file as a binary when you create releases so that addon updaters such as WoWUp can retrieve new versions. I've created a zip file using github and attached it to this ticket if you would like to add it to the latest release.
[minarch-9.2.0.zip](https://github.com/MrFox42/minarch/files/8636376/minarch-9.2.0.zip)
If you would like to receive support though addon sites such as Curse, I would ask that you please consider using other sites such as wago.io in addition to Curse.
Thank you.

**Comment by med0rian** [comment]
Like to push this a little bit - It would be very nice when we can Update this Addon via WoWUp :)

**Comment by marthammor** [comment]
Thank you for your time and effort in doing this!

**Comment by MrFox42** [comment]
Should be available on Wago now. Does anyone know if I need to do anything else to make it available on WowUp?

**Comment by marthammor** [comment]
WowUp can pull from Wago and since you're now including the zip file in github, WowUp can also be pointed to the releases section here and it'll grab the newest zip file release.

**Comment by MrFox42** [comment]
It's now available on WowUp as well, thanks for the info.
